export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
